# Generated by Django 4.0.1 on 2022-01-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_basket',
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=256)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('discount_amount', models.FloatField()),
                ('effective_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket_api.customerbasket')),
            ],
            options={
                'db_table': 'basket_items',
            },
        ),
    ]
